### ISSUE TITLE
[Bug]: Footer undefined in the getConnectLayout

### ISSUE THREAD

**Issue by brf153** [RocketChat/Apps.Notion#32]
### What happened?

I was expecting to get the avatar_url and name in the footer after authorizing but I am getting undefined.

### Steps to reproduce

Just connect to notion and check the first message you get after coming back to rocket chat room.

### Relevant ScreenShots

![Screenshot from 2024-01-13 11-46-19](https://github.com/RocketChat/Apps.Notion/assets/107868772/6453bd7f-4ab3-4d0f-9a54-b06ecfb95692)

### Version

v6.5.2

### What browsers are you seeing the problem on?

Chrome

**Comment by brf153** [comment]
I have done a thorough research on this issue. The notion's API has changed a bit. Now, after authorizing, Notion does not return avatar_url and name in the response. The sample response of the endpoint is
```
{
  "access_token": "e202e8c9-0990-40af-855f-ff8f872b1ec6c",
  "bot_id": "b3414d659-1224-5ty7-6ffr-cc9d8773drt601288f",
  "duplicated_template_id": null,
  "owner": {
    "workspace": true
  },
  "workspace_icon": "https://website.domain/images/image.png",
  "workspace_id": "j565j4d7x3-2882-61bs-564a-jj9d9ui-c36hxfr7x",
  "workspace_name": "Ada's Notion Workspace"
}
```

For the userInfo, we now have a get request to the user's endpoint from which we will retrieve all the data of the users in the database. 
![Screenshot from 2024-01-13 13-18-54](https://github.com/RocketChat/Apps.Notion/assets/107868772/14ca5f43-bf36-4120-95a2-62e623e7d1db)


Initially, if the user capabilities have been set to none in the public integration settings then we will get a 403 error. So, we will have to change the setting to "User information without email addresses" or "User information with email addresses". After changing the settings, we will get the desired response from the API which will contain all the user's data including avatar_url and name.

**Comment by Nabhag8848** [comment]
Hey, i believe its just the matter of capabilities set by the org admin and notion api hasn't been changed.

![Screenshot_2024-01-13-13-42-49-15_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/RocketChat/Apps.Notion/assets/65061890/1a0890bb-a5af-4aba-a029-66ec7f024493)

we have a case, where if email and name capabilities has been denied we remove the footer itself to avoid broken UI.

**Comment by brf153** [comment]
@Nabhag8848 yeah I am getting it now. So, do we need to show the name and avatar_url of the owner of the workspace and not the user who might be the member of the workspace trying to access the workspace?

**Comment by Nabhag8848** [comment]
Currently its the user avatar and name, person who connected the workspace each one  of them have their own name and avatar and its what we want currently but we need to handle the case if the org admin denied the capabilities of giving access to email and name to app. in that case just don't show the footer.

**Comment by brf153** [comment]
@Nabhag8848 But, I think that we are displaying the owner's name and avatar_url in the footer because, when I query the '/user/me' endpoint, it returns the name and avatar_url associated with the public integration.
![Screenshot from 2024-01-13 15-04-51](https://github.com/RocketChat/Apps.Notion/assets/107868772/1819d4c4-268f-403e-92aa-86daf87512cb)

If I keep the default settings which are {name, avatar_url} = owner.user (data of the owner inside the authorization response), then it shows me the name and avatar_url of the owner.
![Screenshot from 2024-01-13 15-05-04](https://github.com/RocketChat/Apps.Notion/assets/107868772/80f8ed7c-a85f-4652-ae7e-4f74dc290299)

**Comment by brf153** [comment]
Should I keep the default changes?

**Comment by Nabhag8848** [comment]
@brf153  I connected to your workspace, and its working as expected. `/users/me` gives bot user avatar_url which you provided in dashboard  when creating  key of notion. There is difference between person and bot in notion. check that.
<img width="574" alt="Close" src="https://github.com/RocketChat/Apps.Notion/assets/65061890/60b2e69a-940e-41ea-9347-2069e10e79b3">

Can you close this issues, as i don't have permission currently ?

**Comment by brf153** [comment]
> @brf153  I connected to your workspace, and its working as expected. `/users/me` gives bot user avatar_url which you provided in dashboard  when creating  key of notion. There is difference between person and bot in notion. check that.
> <img width="574" alt="Close" src="https://github.com/RocketChat/Apps.Notion/assets/65061890/60b2e69a-940e-41ea-9347-2069e10e79b3">
> 
> Can you close this issue, as i don't have permission currently ?
> 

Oki bhaiya. Also thank you for clarifying this.
