### ISSUE TITLE
[Bug] Remove Emojis From Markdown Text including message option

### ISSUE THREAD

**Issue by Nabhag8848** [RocketChat/Apps.Notion#37]
### What happened?

- There should be no emojis within App, in options or notification messages of app as it is against the design principles mentioned in apps docs.

### Steps to reproduce

- [ ] Find and Report here where there are emojis
- [ ] Once Acknowledge Start working for removing emojis. 
- [ ] For Eg: Remove emoji from Options: Send to Page and Send to New Page

### Relevant ScreenShots

<img width="214" alt="Remove" src="https://github.com/RocketChat/Apps.Notion/assets/65061890/1adc53e9-266c-49ce-8133-ae7acbba08d2">

### Version

v6.5

### What browsers are you seeing the problem on?

Chrome

**Comment by brf153** [comment]
/notion help
![Screenshot from 2024-01-18 19-21-30](https://github.com/RocketChat/Apps.Notion/assets/107868772/20b82821-adc0-495c-a9f6-a26945481604)

**Comment by brf153** [comment]
/notion connect
![Screenshot from 2024-01-18 19-22-38](https://github.com/RocketChat/Apps.Notion/assets/107868772/9a7eba88-90f5-4ece-aed3-b19bcfb4d5ae)

**Comment by brf153** [comment]
@Nabhag8848 Do we have to remove the emojis from here as well?
![Screenshot from 2024-01-18 19-23-30](https://github.com/RocketChat/Apps.Notion/assets/107868772/1bdd2e6b-aa39-4ac2-afe1-20326514a284)

**Comment by brf153** [comment]
/notion connect notification after connecting
![Screenshot from 2024-01-18 19-25-08](https://github.com/RocketChat/Apps.Notion/assets/107868772/aefa15a5-d716-48c5-a000-5c8722bb369d)

**Comment by Nabhag8848** [comment]
Reaction 🚀: Yes.
No Reaction: You don't have to.

**Comment by brf153** [comment]
/notion disconnect
![Screenshot from 2024-01-18 19-28-44](https://github.com/RocketChat/Apps.Notion/assets/107868772/258abddb-dd5f-4b23-b48a-cd4fc18a375a)

**Comment by brf153** [comment]
/notion comment when user is not connected
![Screenshot from 2024-01-18 19-29-31](https://github.com/RocketChat/Apps.Notion/assets/107868772/3b64eafb-622e-42c0-9c66-2d26375d1791)

**Comment by Nabhag8848** [comment]
- Remove Emojis if it is simple Text.

**Comment by brf153** [comment]
/notion create dialog box dropdown
![Screenshot from 2024-01-18 21-23-40](https://github.com/RocketChat/Apps.Notion/assets/107868772/f77a96b4-512c-4257-8855-e283fb713bcc)

**Comment by brf153** [comment]
/notion create db dialog box dropdown
![Screenshot from 2024-01-18 21-25-40](https://github.com/RocketChat/Apps.Notion/assets/107868772/e46dc86b-4660-4d67-bf57-f2c21af3c912)

**Comment by brf153** [comment]
/notion share dialog box dropdown
![Screenshot from 2024-01-18 21-32-15](https://github.com/RocketChat/Apps.Notion/assets/107868772/4e4e632d-b5a7-4631-89e9-67076c814c12)

**Comment by brf153** [comment]
after creating new page
![Screenshot from 2024-01-18 21-34-01](https://github.com/RocketChat/Apps.Notion/assets/107868772/9b5c2277-e06f-42a9-b356-eaf099a284e5)

**Comment by brf153** [comment]
After sharing page
![Screenshot from 2024-01-18 21-35-57](https://github.com/RocketChat/Apps.Notion/assets/107868772/407ded83-7396-4ba2-bab5-45702fbc591a)

**Comment by brf153** [comment]
After creating a new db
![Screenshot from 2024-01-18 21-39-40](https://github.com/RocketChat/Apps.Notion/assets/107868772/385a2bb6-35f8-4c7e-bc71-4178db78a257)

**Comment by brf153** [comment]
"More" dropdown when hovered over a create new page, create new db, share page message
![Screenshot from 2024-01-18 21-43-59](https://github.com/RocketChat/Apps.Notion/assets/107868772/f78d3764-9f12-4a83-831b-db1eab1c57fc)

**Comment by brf153** [comment]
> "More" dropdown when hovered over a create new page, create new db, share page message ![Screenshot from 2024-01-18 21-43-59](https://private-user-images.githubusercontent.com/107868772/297808765-f78d3764-9f12-4a83-831b-db1eab1c57fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTQ4NDcsIm5iZiI6MTcwNTU5NDU0NywicGF0aCI6Ii8xMDc4Njg3NzIvMjk3ODA4NzY1LWY3OGQzNzY0LTlmMTItNGE4My04MzFiLWRiMWVhYjFjNTdmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxNjE1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDM2ZDVhMGVmMzllMmJmZTBmZDg4M2MyMjg1YTY4ZjZjNGNjZDYxZmM2MmUxYTQ4MjVmODE0ODI2MTY2MzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GShEcqV6QnSpqqYH0sVVCsvEJIhEJg0BHHncdo8cQXI)

@Nabhag8848 bhaiya do I also have to work on this? I don't think this is related to Apps.Notion.

**Comment by Nabhag8848** [comment]
Remove ✨ from everywhere, 
also, In drop-down can you have a mechanism in which you remove the emojis of page and pile of books only in case of searchDatabase and searchPage but not in searchPageOrDatabase Component.

Those emojis are there in createDatabase feature to differentiate between page if its the part of notion table or its just the page.

**Comment by Nabhag8848** [comment]
> "More" dropdown when hovered over a create new page, create new db, share page message
> ![Screenshot from 2024-01-18 21-43-59](https://github.com/RocketChat/Apps.Notion/assets/107868772/f78d3764-9f12-4a83-831b-db1eab1c57fc)
> 

Remove from sendtopage and sendtonewpage

**Comment by brf153** [comment]
@Nabhag8848 oki I will check and work on it.

**Comment by Nabhag8848** [comment]
> > "More" dropdown when hovered over a create new page, create new db, share page message ![Screenshot from 2024-01-18 21-43-59](https://private-user-images.githubusercontent.com/107868772/297808765-f78d3764-9f12-4a83-831b-db1eab1c57fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTQ4NDcsIm5iZiI6MTcwNTU5NDU0NywicGF0aCI6Ii8xMDc4Njg3NzIvMjk3ODA4NzY1LWY3OGQzNzY0LTlmMTItNGE4My04MzFiLWRiMWVhYjFjNTdmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxNjE1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDM2ZDVhMGVmMzllMmJmZTBmZDg4M2MyMjg1YTY4ZjZjNGNjZDYxZmM2MmUxYTQ4MjVmODE0ODI2MTY2MzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GShEcqV6QnSpqqYH0sVVCsvEJIhEJg0BHHncdo8cQXI)
> 
> @Nabhag8848 bhaiya do I also have to work on this? I don't think this is related to Apps.Notion. 

Plz note that, send to page and send to new page is a feature where users can save important message, links or customer queries into notion table or page.

**Comment by Nabhag8848** [comment]
Check Feature 10 to know more
https://github.com/Nabhag8848/Google-Summer-of-Code
