### ISSUE TITLE
[Bug] Search of Pages and / or Database in SearchComponent Currently Doesn't Support Pagination

### ISSUE THREAD

**Issue by Nabhag8848** [RocketChat/Apps.Notion#38]
### What happened?

- Current Implemenatation doesn't support pagination of Searching pages and/ or databases. 
- Api endpoint of Search Page, Returns maximum of 100 pages 
- https://developers.notion.com/reference/post-search
- methods searchPages, searchDatabase, SearchPagesandDatabases under NotionSDK, (maybe more) uses this API.

### Steps to reproduce

- [ ] Improve methods such a way that it gets all the avaialable pages and / or databases.
- [ ] Check if there is performance issue while doing this.

### Version

v6.5

### What browsers are you seeing the problem on?

Chrome

**Comment by brf153** [comment]
@Nabhag8848 working on this issue.

**Comment by brf153** [comment]
How I Will Implement the Changes:

1) After reviewing Notion's API guide, I realized that the response allows a maximum of 100 items. If the number of items exceeds 100, the response will contain 'has_more: true' along with a cursor value. To retrieve additional items, we need to pass this cursor value back to Notion's API, either through a query in a GET request or using the body in a POST request.
![Screenshot from 2024-01-20 12-02-06](https://github.com/RocketChat/Apps.Notion/assets/107868772/5f9afe8f-c0af-4519-9dea-5078cb2a9133)

2) Consequently, I will implement a mechanism to check 'has_more' in every response. If 'has_more' is true, we will extract the cursor value from the response and send another request, continuing this process until 'has_more' becomes false. Subsequently, we will merge all the responses into one array, which will be passed as the final response for subsequent implementations.

3) To verify the implementation and address potential performance issues, I will initially set the 'page_size' to 10 and create more than 10 pages in my workspace. Following this, I will send the query and assess its functionality to ensure its effectiveness.

**Comment by brf153** [comment]
> How I Will Implement the Changes:
> 
> 1. After reviewing Notion's API guide, I realized that the response allows a maximum of 100 items. If the number of items exceeds 100, the response will contain 'has_more: true' along with a cursor value. To retrieve additional items, we need to pass this cursor value back to Notion's API, either through a query in a GET request or using the body in a POST request.
>    ![Screenshot from 2024-01-20 12-02-06](https://private-user-images.githubusercontent.com/107868772/298266047-5f9afe8f-c0af-4519-9dea-5078cb2a9133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzM0NzEsIm5iZiI6MTcwNTczMzE3MSwicGF0aCI6Ii8xMDc4Njg3NzIvMjk4MjY2MDQ3LTVmOWFmZThmLWMwYWYtNDUxOS05ZGVhLTUwNzhjYjJhOTEzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwNjQ2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjA2NzY3MjIxYzE4Yjk1ZTVlYzkwYzg1NTliZWY1MWNiM2M0ZjRmYjk3MjBhYzFhOTEyZjlkNzY1NGQ0NGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MOQIIYzD1fMYD0Ocrw7ZdJ5DRp_ZZjTSIivHhmt7UJM)
> 2. Consequently, I will implement a mechanism to check 'has_more' in every response. If 'has_more' is true, we will extract the cursor value from the response and send another request, continuing this process until 'has_more' becomes false. Subsequently, we will merge all the responses into one array, which will be passed as the final response for subsequent implementations.
> 3. To verify the implementation and address potential performance issues, I will initially set the 'page_size' to 10 and create more than 10 pages in my workspace. Following this, I will send the query and assess its functionality to ensure its effectiveness.

@Nabhag8848 Could you please review this and advise if I should proceed with this approach?

**Comment by Nabhag8848** [comment]
> How I Will Implement the Changes:
> 
> 1. After reviewing Notion's API guide, I realized that the response allows a maximum of 100 items. If the number of items exceeds 100, the response will contain 'has_more: true' along with a cursor value. To retrieve additional items, we need to pass this cursor value back to Notion's API, either through a query in a GET request or using the body in a POST request.
>    ![Screenshot from 2024-01-20 12-02-06](https://private-user-images.githubusercontent.com/107868772/298266047-5f9afe8f-c0af-4519-9dea-5078cb2a9133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MTcyNDksIm5iZiI6MTcwNTgxNjk0OSwicGF0aCI6Ii8xMDc4Njg3NzIvMjk4MjY2MDQ3LTVmOWFmZThmLWMwYWYtNDUxOS05ZGVhLTUwNzhjYjJhOTEzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQwNjAyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODM2MzM2NmY1NWQ5NmM2NmU2NjdiYThjN2FkYzk1YzgzMWM1ZDIzZDk1NmJkNzFjMjVjZWExNjI5Yzk5OWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R3JZbUNxxh_Z1wmfgLupnth031wsYBQEr0io2g5fr8I)
> 2. Consequently, I will implement a mechanism to check 'has_more' in every response. If 'has_more' is true, we will extract the cursor value from the response and send another request, continuing this process until 'has_more' becomes false. Subsequently, we will merge all the responses into one array, which will be passed as the final response for subsequent implementations.
> 3. To verify the implementation and address potential performance issues, I will initially set the 'page_size' to 10 and create more than 10 pages in my workspace. Following this, I will send the query and assess its functionality to ensure its effectiveness.

- Overall you got the implementation but check by setting page_size to 100 itself, cause larger page_size (>10) is proved to work feasibly. Also note that lesser the number of page_size more the Network request. thus we will try to make minimum network request and get maximum page a each request, I believe will involve recursion concept.

**Comment by brf153** [comment]
@Nabhag8848 how will I check with page_size 100? Will I have to make more than 100 pages to check this?

**Comment by Nabhag8848** [comment]
> @Nabhag8848 how will I check with page_size 100? Will I have to make more than 100 pages to check this?

Edited the Message. Yep Use Api to create it.

**Comment by brf153** [comment]
@Nabhag8848 oki I will do it
