### ISSUE TITLE
[Chore]  Australian dollar Number Format support in Create Table Feature and Some Chores

### ISSUE THREAD

**Issue by Nabhag8848** [RocketChat/Apps.Notion#42]
### What happened?

- There has been some changes in notion api: 
FInd complete change log: https://developers.notion.com/page/changelog

- New ID Field introduced in Notion Table, check if that breaks anything in our app.

- The [verification](https://developers.notion.com/reference/page-property-values#verification) page property was added to the [Page properties](https://developers.notion.com/reference/page-property-values) documentation. see if it breaks and we can improve something.

## [ChangeLog](https://developers.notion.com/page/changelog#september-6---september-7-2023) September 6 - September 7, 2023
- The [updates](https://developers.notion.com/page/changelog#notice-for-an-upcoming-public-api-change) related to the [Formulas 2.0 launch](https://twitter.com/NotionHQ/status/1699828805408550971?s=20) are now live in the Public API. These changes will not impact most developers using the Public API; however, please note that the formatting of [formula.expression](https://developers.notion.com/reference/property-object#formula), which is returned when [retrieving a database](https://developers.notion.com/reference/retrieve-a-database) with a [Formula property](https://developers.notion.com/reference/property-object#formula), has changed. See Notion's Help Center articles for more information on the Formula 2.0 changes:
[Formulas 2.0: How to use Notion’s new and improved formulas with your existing setups](https://www.notion.so/help/guides/new-formulas-whats-changed)
[How to write Notion formulas that extend the capabilities of your databases](https://www.notion.so/help/guides/write-formulas-that-extend-capabilities-of-databases)
- The example for the [Formula database property](https://developers.notion.com/reference/property-object#formula) was updated to align with the new Formula 2.0 launch.
- also read: https://developers.notion.com/page/changelog#august-8---august-22-2023

### Steps to reproduce

- [x] Check if the formula property works as expected in /notion create db. and make changes accordingly.
- [x] as australian dollar has been supported now. under /notion create db if the Notion table includes a number then it should have a number format of australian dollar too. [Check SS below]

### Relevant ScreenShots

<img width="624" alt="Create" src="https://github.com/RocketChat/Apps.Notion/assets/65061890/241bff93-4988-4fa8-a899-0f7897c1b524">

### Version

v6.5

### What browsers are you seeing the problem on?

Chrome

**Comment by Sumitwarrior7** [comment]
I want to work on this issue @Nabhag8848 
Can you please assign me this
