### ISSUE TITLE
[Bug] Fix UI Element text Breaking into two lines when long username

### ISSUE THREAD

**Issue by Nabhag8848** [RocketChat/Apps.Notion#46]
### What happened?

- `onInstallation` message and when running `/notion connect` text in notification is breaking into two lines. we need to make an notification such that it appears in single line even though username is large.

- Incase of `onInstallation` message we need to attach the layout to top the the Hey `username` welcome to notion app message below the layout.

### Steps to reproduce

- `/notion connect` with large username.
- install app having large username

### Relevant ScreenShots

https://github.com/RocketChat/Apps.Notion/assets/65061890/44d6b045-ab52-4021-ab21-8d271f579acd

<img width="669" alt="pic1" src="https://github.com/RocketChat/Apps.Notion/assets/65061890/3f33640e-22eb-47db-ad6f-3a5831ec6050">

### Version

v6.5

### What browsers are you seeing the problem on?

Chrome

**Comment by brf153** [comment]
`Incase of onInstallation message we need to attach the layout to top the the Hey username welcome to notion app message below the layout.`

@Nabhag8848 I did not get this

**Comment by Nabhag8848** [comment]
> `Incase of onInstallation message we need to attach the layout to top the the Hey username welcome to notion app message below the layout.`
> 
> @Nabhag8848 I did not get this

I mean `Hey username welcome to notion app` that text needs below layout so layout info will stick to top. meaning `Hey username welcome to notion app` should be first line incase of `setting up the notion app..`

**Comment by Spiral-Memory** [comment]
@Nabhag8848 , I feel the issue lies here `LayoutBlockType.SECTION` only occupies a certain width. Both of the issue you mentioned, in that the text uses the function `createSectionBlock` and hence causing the issue. I am new to Rocket chat UI Kit, so i am not sure, which will be better to use in this case ?

![image](https://github.com/RocketChat/Apps.Notion/assets/78961432/250e0548-d024-4c20-b9b0-baf225e8f9eb)

Using getCreator  of IModify, full line text can be done, then using createContextBlock that is custom function defined, it can be done.

**Comment by Nabhag8848** [comment]
> @Nabhag8848 , I feel the issue lies here `LayoutBlockType.SECTION` only occupies a certain width. Both of the issue you mentioned, in that the text uses the function `createSectionBlock` and hence causing the issue. I am new to Rocket chat UI Kit, so i am not sure, which will be better to use in this case ?
> 
> ![image](https://github.com/RocketChat/Apps.Notion/assets/78961432/250e0548-d024-4c20-b9b0-baf225e8f9eb)
> 
> Using getCreator  of IModify, full line text can be done, then using createContextBlock that is custom function defined, it can be done. 
> 
> 

Hey, I believe @brf153 is working on this issue. + please please please only work on one issue at a time.

**Comment by Spiral-Memory** [comment]
@Nabhag8848 , Certainly, sir. I apologize if it caused any inconvenience. Well, which issue should I work on, sir? Apart from preserving the message one, as that is a significant issue and requires a lot of discussion to fully understand the implementation. Currently, I am looking for a good first issue to understand the codebase and how RC apps work.

**Comment by brf153** [comment]
@Nabhag8848 I believe there is an issue. For testing purposes, I created a function named sendNotificationWithBlock.
![Screenshot from 2024-01-29 11-54-53](https://github.com/RocketChat/Apps.Notion/assets/107868772/01c345af-ae33-4a15-8912-b5e6beed885f)

Initially, you can observe that I have commented out some code, and I'm not using any blocks at this point. As shown in the picture below, the text is fully visible and does not break.
![Screenshot from 2024-01-29 11-57-12](https://github.com/RocketChat/Apps.Notion/assets/107868772/03219210-2178-41fe-9140-fa9e4d18e7cd)

When I remove the comment (i.e., when I add the block), I only get the block and not the message.

The section block, which we were using earlier, does not allow us to increase the width, causing the text to break.

We have two options: either replace the text with something else like `Hello!👋 Connect your Notion Workspace` without including the name, or consider making an issue in the apps-engine and try to address the problem there.

**Comment by Nabhag8848** [comment]
> @Nabhag8848 I believe there is an issue. For testing purposes, I created a function named sendNotificationWithBlock. ![Screenshot from 2024-01-29 11-54-53](https://private-user-images.githubusercontent.com/107868772/300356186-01c345af-ae33-4a15-8912-b5e6beed885f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NTYwODAsIm5iZiI6MTcwNjU1NTc4MCwicGF0aCI6Ii8xMDc4Njg3NzIvMzAwMzU2MTg2LTAxYzM0NWFmLWFlMzMtNGExNS04OTEyLWI1ZTZiZWVkODg1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxOTE2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2FiMWJkNjk3YzJlOTc1NmIzMDg1MDNhYTRkOWI5ZWNhYWJhNTM5ZWE3ZDM4OTUyYWEyM2U0NjUzYTAxZTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GHxKu1NZmkCx6HFryfmYTFeuBXneYA-qoVb5fFco_5g)
> 
> Initially, you can observe that I have commented out some code, and I'm not using any blocks at this point. As shown in the picture below, the text is fully visible and does not break. ![Screenshot from 2024-01-29 11-57-12](https://private-user-images.githubusercontent.com/107868772/300356093-03219210-2178-41fe-9140-fa9e4d18e7cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NTYwODAsIm5iZiI6MTcwNjU1NTc4MCwicGF0aCI6Ii8xMDc4Njg3NzIvMzAwMzU2MDkzLTAzMjE5MjEwLTIxNzgtNDFmZS05MTQwLWZhOWU0ZDE4ZTdjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxOTE2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWVlMTcxMjE5M2VkNjY5NDA5OTVjYTVlYzQ3NTVhMWZjNWExOWU5NmJiOWYyNGQzNDhjMmE4NTM5MGU4MTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z5DxIhCiIq5o-24AAEhHnhDFmabXn8-00GUHdalJaZ8)
> 
> When I remove the comment (i.e., when I add the block), I only get the block and not the message. ![Screenshot from 2024-01-29 12-11-19](https://private-user-images.githubusercontent.com/107868772/300357761-84b34d28-48fb-4911-bcf2-cf73e95655c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NTYwODAsIm5iZiI6MTcwNjU1NTc4MCwicGF0aCI6Ii8xMDc4Njg3NzIvMzAwMzU3NzYxLTg0YjM0ZDI4LTQ4ZmItNDkxMS1iY2YyLWNmNzNlOTU2NTVjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxOTE2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2NlNTU5ODA4MzdmZGNlNDBiMThkNDI5NTU1MDUxOGE0NDIzODUyMzkxNTVmZTM2OTE4ZmNkZGEwMmQxODZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GMIyrlkcZ6A-0HgqACFppM9NRd79o8w6eAA4UXw68eg)
> 
> The section block, which we were using earlier, does not allow us to increase the width, causing the text to break.
> 
> We have two options: either replace the text with something else like `Hello!👋 Connect your Notion Workspace` without including the name, or consider making an issue in the apps-engine and try to address the problem there.

yep. new uikit sets either text or block at a time. 
Can we have button as an attachment does that solve our problem or we would face the same issue ? if that doesn't we can change text to `Hey ${username} !`.

**Comment by brf153** [comment]
Oki I will check it

**Comment by brf153** [comment]
@Nabhag8848 I have implemented the functionality you stated above. I am sending the action block as an attachment. Although the UI might not be perfect, it is working fine. 
![Screenshot from 2024-01-30 12-09-00](https://github.com/RocketChat/Apps.Notion/assets/107868772/fbb3acf0-8d1c-4e34-bfbe-6c34be6bf173)

**Comment by brf153** [comment]
Shall I raise a pr for these changes?

**Comment by Nabhag8848** [comment]
> Shall I raise a pr for these changes?

Can we make a button variant to primary so we can have a blue background.+ change text to `Connect to Workspace` to maintain consistency across app.

**Comment by brf153** [comment]
I have made the changes for onInstall. It looks like
![Screenshot from 2024-01-30 14-39-49](https://github.com/RocketChat/Apps.Notion/assets/107868772/a1216a83-d007-4d95-839c-55cc7e325ee2)

**Comment by brf153** [comment]
Can we add custom css to our code for the ui kit? I am not being able to add the style: "primary" to the attachment's block. But, when I make changes in the devtools of chrome, I am being able to make the required changes.
![Screenshot from 2024-01-30 14-49-10](https://github.com/RocketChat/Apps.Notion/assets/107868772/3953d3b7-ec68-4914-90bd-742c23e7d566)

**Comment by brf153** [comment]
Without custom css our button and message will look like
![Screenshot from 2024-01-30 14-56-23](https://github.com/RocketChat/Apps.Notion/assets/107868772/d5fcc9c7-1508-4a64-9771-9e96ea5284c9)

**Comment by Nabhag8848** [comment]
> Can we add custom css to our code for the ui kit? I am not being able to add the style: "primary" to the attachment's block. But, when I make changes in the devtools of chrome, I am being able to make the required changes. ![Screenshot from 2024-01-30 14-49-10](https://private-user-images.githubusercontent.com/107868772/300746936-3953d3b7-ec68-4914-90bd-742c23e7d566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjAyMTcsIm5iZiI6MTcwNjYxOTkxNywicGF0aCI6Ii8xMDc4Njg3NzIvMzAwNzQ2OTM2LTM5NTNkM2I3LWVjNjgtNDkxNC05MGJkLTc0MmMyM2U3ZDU2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMzA1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmEwMzhlZWQ5MGZkZGUxMmQ0ZjczOWE2NTk3MDIzNjliY2ZmY2E3YWJiYTQ1YzZlMjI3N2ZhNzY2ZDcyM2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mgcFPOZfa2r7_7-1L-6NY4sF1tB_UgGlP9-CjqOXavU)

we can't as far as i know, hacks can go again RC design principles.

**Comment by Nabhag8848** [comment]
> Without custom css our button and message will look like ![Screenshot from 2024-01-30 14-56-23](https://private-user-images.githubusercontent.com/107868772/300749336-d5fcc9c7-1508-4a64-9771-9e96ea5284c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjAyMTcsIm5iZiI6MTcwNjYxOTkxNywicGF0aCI6Ii8xMDc4Njg3NzIvMzAwNzQ5MzM2LWQ1ZmNjOWM3LTE1MDgtNGE2NC05NzcxLTllOTZlYTUyODRjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMzA1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmM4M2E3MGMzZGExNTNlYTVmZTlhZDRkNDg4NDIyNzI0MTUxYjY1ZDg4MzBhYTQ4NTNlMjNhYzNlMzEzZTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.THktdFG8ZUhI_JPIJpb0qzDfiS6gWbfjZDOckSFKvj8)

Are we using PRIMARY button anywhere else except the submit button of modal and Comment Button ? if not, this won't break consistency across app, we are good to go with this.

**Comment by Nabhag8848** [comment]
> @Nabhag8848 I have made the changes for onInstall. It looks like ![Screenshot from 2024-01-30 14-39-49](https://private-user-images.githubusercontent.com/107868772/300743958-a1216a83-d007-4d95-839c-55cc7e325ee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjAyMTcsIm5iZiI6MTcwNjYxOTkxNywicGF0aCI6Ii8xMDc4Njg3NzIvMzAwNzQzOTU4LWExMjE2YTgzLWQwMDctNGQ5NS04MzljLTU1Y2M3ZTMyNWVlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMzA1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTE3ODJkNDhkZGI1OWIzNzg2M2NhODRiNzg5YjEwZGYxNGM5MjExZGE2MjJlYjIwYWJkYzhjYjA0MWQ1ODU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.avpbMoiI1lljMj7_G6LkUcw5QBVO5QhC2BttaJm72V0)

Can we have that greeting on the second message ? also as we see, having two notification on install, can we make it one somehow and match the UI ? Can we have that layout as attachment and look as if it is attached below the notification with setup information like connect to workspace button.

**Comment by brf153** [comment]
> > Without custom css our button and message will look like ![Screenshot from 2024-01-30 14-56-23](https://private-user-images.githubusercontent.com/107868772/300749336-d5fcc9c7-1508-4a64-9771-9e96ea5284c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjAyMTcsIm5iZiI6MTcwNjYxOTkxNywicGF0aCI6Ii8xMDc4Njg3NzIvMzAwNzQ5MzM2LWQ1ZmNjOWM3LTE1MDgtNGE2NC05NzcxLTllOTZlYTUyODRjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMzA1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmM4M2E3MGMzZGExNTNlYTVmZTlhZDRkNDg4NDIyNzI0MTUxYjY1ZDg4MzBhYTQ4NTNlMjNhYzNlMzEzZTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.THktdFG8ZUhI_JPIJpb0qzDfiS6gWbfjZDOckSFKvj8)
> 
> Are we using PRIMARY button anywhere else except the submit button of modal and Comment Button ? if not, this won't break consistency across app, we are good to go with this.

![Screenshot from 2024-01-30 19-26-43](https://github.com/RocketChat/Apps.Notion/assets/107868772/163c5dc4-82d9-4805-90e2-664fcef75062)

Shall I make these the same as I have done for the `/notion connect` command?

**Comment by brf153** [comment]
![Screenshot from 2024-01-30 19-29-02](https://github.com/RocketChat/Apps.Notion/assets/107868772/9a0f1f97-3296-46f0-a23b-08d85278901b)
By submit button of modal, do you mean these buttons?

**Comment by brf153** [comment]
> > @Nabhag8848 I have made the changes for onInstall. It looks like ![Screenshot from 2024-01-30 14-39-49](https://private-user-images.githubusercontent.com/107868772/300743958-a1216a83-d007-4d95-839c-55cc7e325ee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjAyMTcsIm5iZiI6MTcwNjYxOTkxNywicGF0aCI6Ii8xMDc4Njg3NzIvMzAwNzQzOTU4LWExMjE2YTgzLWQwMDctNGQ5NS04MzljLTU1Y2M3ZTMyNWVlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMzA1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTE3ODJkNDhkZGI1OWIzNzg2M2NhODRiNzg5YjEwZGYxNGM5MjExZGE2MjJlYjIwYWJkYzhjYjA0MWQ1ODU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.avpbMoiI1lljMj7_G6LkUcw5QBVO5QhC2BttaJm72V0)
> 
> Can we have that greeting on the second message ? also as we see, having two notification on install, can we make it one somehow and match the UI ? Can we have that layout as attachment and look as if it is attached below the notification with setup information like `connect to workspace` button, if thats possible lemme know.

I can make something like
![Screenshot from 2024-01-30 20-17-37](https://github.com/RocketChat/Apps.Notion/assets/107868772/aec6ec2f-2d38-4d08-af92-f3efaf53f801)
I think the layout you are talking about is the preview block which is having the notion's image, the header, the footer, and the text element. I have checked but I did not get anyway to send blocks as the attachment. The only block which we can send is the action block which is already defined in the IMessageAttachment

**Comment by Nabhag8848** [comment]
> > > @Nabhag8848 I have made the changes for onInstall. It looks like ![Screenshot from 2024-01-30 14-39-49](https://private-user-images.githubusercontent.com/107868772/300743958-a1216a83-d007-4d95-839c-55cc7e325ee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjAyMTcsIm5iZiI6MTcwNjYxOTkxNywicGF0aCI6Ii8xMDc4Njg3NzIvMzAwNzQzOTU4LWExMjE2YTgzLWQwMDctNGQ5NS04MzljLTU1Y2M3ZTMyNWVlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMzA1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTE3ODJkNDhkZGI1OWIzNzg2M2NhODRiNzg5YjEwZGYxNGM5MjExZGE2MjJlYjIwYWJkYzhjYjA0MWQ1ODU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.avpbMoiI1lljMj7_G6LkUcw5QBVO5QhC2BttaJm72V0)
> > 
> > 
> > Can we have that greeting on the second message ? also as we see, having two notification on install, can we make it one somehow and match the UI ? Can we have that layout as attachment and look as if it is attached below the notification with setup information like `connect to workspace` button, if thats possible lemme know.
> 
> I can make something like ![Screenshot from 2024-01-30 20-17-37](https://private-user-images.githubusercontent.com/107868772/300852116-aec6ec2f-2d38-4d08-af92-f3efaf53f801.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNzc1NzEsIm5iZiI6MTcwNzA3NzI3MSwicGF0aCI6Ii8xMDc4Njg3NzIvMzAwODUyMTE2LWFlYzZlYzJmLTJkMzgtNGQwOC1hZjkyLWYzZWZhZjUzZjgwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQyMDA3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWE0YWQyNzZmYWQzMjUwOTNjN2UwOGRhODhhMzkxZTdmMjU1MjMzNDFjODM4NDAyNzg1ZGE0YjI0NTc1Y2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5RH1I0kRCB0sKuaPv_YY4wdEuxP0vHChPiTXx9EfPfI) I think the layout you are talking about is the preview block which is having the notion's image, the header, the footer, and the text element. I have checked but I did not get anyway to send blocks as the attachment. The only block which we can send is the action block which is already defined in the IMessageAttachment

@brf153 This Looks Good !

**Comment by Nabhag8848** [comment]
> > > Without custom css our button and message will look like ![Screenshot from 2024-01-30 14-56-23](https://private-user-images.githubusercontent.com/107868772/300749336-d5fcc9c7-1508-4a64-9771-9e96ea5284c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjAyMTcsIm5iZiI6MTcwNjYxOTkxNywicGF0aCI6Ii8xMDc4Njg3NzIvMzAwNzQ5MzM2LWQ1ZmNjOWM3LTE1MDgtNGE2NC05NzcxLTllOTZlYTUyODRjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMzA1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmM4M2E3MGMzZGExNTNlYTVmZTlhZDRkNDg4NDIyNzI0MTUxYjY1ZDg4MzBhYTQ4NTNlMjNhYzNlMzEzZTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.THktdFG8ZUhI_JPIJpb0qzDfiS6gWbfjZDOckSFKvj8)
> > 
> > 
> > Are we using PRIMARY button anywhere else except the submit button of modal and Comment Button ? if not, this won't break consistency across app, we are good to go with this.
> 
> ![Screenshot from 2024-01-30 19-26-43](https://private-user-images.githubusercontent.com/107868772/300832060-163c5dc4-82d9-4805-90e2-664fcef75062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNzcwOTUsIm5iZiI6MTcwNzA3Njc5NSwicGF0aCI6Ii8xMDc4Njg3NzIvMzAwODMyMDYwLTE2M2M1ZGM0LTgyZDktNDgwNS05MGUyLTY2NGZjZWY3NTA2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQxOTU5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjY4YmFjZTNkZDIwMTEyMmVjYTYwZDZkODZhNWYzYTJlNThmZmNkODMwOGUzYjg0OTNhOTBkNGRhZWNiNGNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IFUH-AN_esPnc7b-SjQHn9OUjwsB48msMhLV5k26fyk)
> 
> Shall I make these the same as I have done for the `/notion connect` command?

@brf153 having button as attachment would break this buttons variation and will force us to change that to grey (not primary) which we can avoid.

**Comment by Nabhag8848** [comment]
@brf153 Lets just have `Connect your Notion Workspace`
<img width="414" alt="Final" src="https://github.com/RocketChat/Apps.Notion/assets/65061890/cef73469-f1f1-48ed-b36d-cfbf595d95b5">

**Comment by brf153** [comment]
@Nabhag8848 what I understood is
i) I will change the onInstall text to
![Screenshot from 2024-01-30 20-17-37](https://github.com/RocketChat/Apps.Notion/assets/107868772/aec6ec2f-2d38-4d08-af92-f3efaf53f801)
ii) I will simply change the `/notion connect` text to Connect you Notion Workspace.

Do I need to make any further changes?
