### ISSUE TITLE
[Bug]: In the Create Page or Record modal, the title input text element is always visible.

### ISSUE THREAD

**Issue by Spiral-Memory** [RocketChat/Apps.Notion#52]
### What happened?

In the Create Page or Database modal, when selecting a database, a different set of inputs has to be filled. Conversely, when selecting a page, only the title should be filled. However, the title input is visible at all times, even when nothing is selected. This is unexpected behavior because, for both databases and pages, the input requirements are different.

### Steps to reproduce

1. Set up the Rocket Chat Server and install the Notion App following the documentation.
2. Navigate to the Notion Bot.
3. Type /notion create to open the modal.
4. Even if there is no page selected, the title bar is still visible. This has no meaning and constitutes unexpected behavior.

### Relevant ScreenShots

![Screenshot from 2024-01-30 02-31-04](https://github.com/RocketChat/Apps.Notion/assets/78961432/435d0c5e-f912-4d18-8b54-7e3931e3fab1)

### Version

v6.6.0-develop

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by Spiral-Memory** [comment]
@Nabhag8848 , As only the title property is relevant to the page, and the database has its own additional properties along with title, displaying the title input even when nothing is selected is unexpected behavior. I have fixed the issue. If you also think this is a problem, please review my PR, and I would appreciate your feedback.

**Comment by Nabhag8848** [comment]
Great Addition. 🚀 Will review, once i get some room.

**Comment by Spiral-Memory** [comment]
Thank you for your appreciation, sir. Yes, sir, I do understand that in any such case when I am making a big change, rest assured I will first confirm with the maintainers. 

Since this was a small addition, I made a PR on my own as I felt it was a non-user-friendly bug.
