### ISSUE TITLE
[Bug] Missing or Invalid redirect_uri

### ISSUE THREAD

**Issue by DILPREET1910** [RocketChat/Apps.Notion#55]
### What happened?

![image](https://github.com/RocketChat/Apps.Notion/assets/81746463/822a5118-86b0-45c2-a725-f10d09cb5c70)
running rocket.chat on local machine.
Installed using docker.

The Apps.Notion was installed using the steps in the readme.
`/notion` command is working. It is showing the list of valid commands.
When i do `/notion create` and open the link to connect to workspace i am getting the above error.

I have set client id and secrete correctly.
below is the webhook of the bot
`http://localhost:3000/api/apps/public/<Some-key-i-don't-know-whether-it-is-save-to-share-on-github>/webhook` 

Also when i do `curl -X GET http://localhost:3000/api/apps/public/<Some-key-i-don't-know-whether-it-is-save-to-share-on-github>/webhook`
output: `Cannot read property 'roomId' of undefined`

### Steps to reproduce

1. `/notion create` in rocket.chat channel
2. open link to connect to workspace
3. above error

### Version

v6.5

### What browsers are you seeing the problem on?

Chrome

**Comment by Sumitwarrior7** [comment]
Use the latest rocket.chat server 
Version : 6.5.3

i was getting something similar problem, once i updated my rocket.chat server, my issue got solved

**Comment by Nabhag8848** [comment]
@DILPREET1910 Are you still facing this issue or @Sumitwarrior7 solves this ?

**Comment by DILPREET1910** [comment]
> Use the latest rocket.chat server Version : 6.5.3
> 
> i was getting something similar problem, once i updated my rocket.chat server, my issue got solved

@Sumitwarrior7 i upgraded rocket chat to 6.5.3 but this issue still persists.

Additional information: the authorisation url in the notion integrations site does not show the above invalid or missing redirect_uri. In this url, the redirect_uri param has the link to redirect me to a site which i have specified in the notions integration page. Whereas when i open the link that appears after `/notion connect` the redirect_uri contains the above webhook.

**Comment by DILPREET1910** [comment]
> @DILPREET1910 Are you still facing this issue or @Sumitwarrior7 solves this ? and just to confirm have you setup the notion app and provided client and secrets of your notion workspace

Yup i have created a new public integration and have provided the client id and secrets correctly to the App.Notion settings page

**Comment by Nabhag8848** [comment]
> > @DILPREET1910 Are you still facing this issue or @Sumitwarrior7 solves this ? and just to confirm have you setup the notion app and provided client and secrets of your notion workspace
> 
> Yup i have created a new public integration and have provided the client id and secrets correctly to the App.Notion settings page

@DILPREET1910 Provide Webhook redirect URI in Public Notion Integration you created in Notion Platform, from where you get that Client id and secrets.

Redirect URI: `http://localhost:3000/api/apps/public/fb6e4e74-f99d-41b6-96da-2486e9aafea8/webhook`
