### ISSUE TITLE
[Bug] View page command is not visible when the list of available commands is shown

### ISSUE THREAD

**Issue by anjy7** [RocketChat/Apps.Notion#56]
### What happened?

/notion view command needs to be added to the list of commands

### Steps to reproduce

type `/notion` to see the list of commands

### Relevant ScreenShots

![image](https://github.com/RocketChat/Apps.Notion/assets/92802904/5d2d32c4-4146-481e-8f45-2d11284e1a0e)

### Version

v6.2.2

### What browsers are you seeing the problem on?

Firefox

**Comment by anjy7** [comment]
I'm willing to add the command if this bug is accepted @Nabhag8848 :rocket:

**Comment by Nabhag8848** [comment]
its there in PR 31, we haven't merge that PR, yet cause view page has lot of limitations some can't be handled and will generate mess in main branch.
- #31
