### ISSUE TITLE
[Feat] : Unnecessary dropdown in Create Page or Record modal

### ISSUE THREAD

**Issue by Sumitwarrior7** [RocketChat/Apps.Notion#63]
### What do we need?

There is already a command for creating databases which displays modal for database creation

But still Create Page or Record modal is having a dropdown for database creation which in my opinion unnecessary for the Create Page or Record modal which is intended to create page or record 

### Acceptance Criteria

Steps to reproduce
1) Go to the Notion Bot.
2) Write /notion create to open the modal.
3) You will see the dropdown there

### Relevant ScreenShots

![Screenshot from 2024-02-04 23-05-29](https://github.com/RocketChat/Apps.Notion/assets/108853577/02006d07-0029-4174-8f7f-f77adb755d7d)

**Comment by Sumitwarrior7** [comment]
@Nabhag8848 bhaiya what do you think of it?

**Comment by Nabhag8848** [comment]
its there for users to quickly naviate to create database if they couldn't find there required notion table and want to create new notion table.

**Comment by Sumitwarrior7** [comment]
> its there for users to quickly naviate to create database if they couldn't find there required notion table and want to create new notion table.

Got it @Nabhag8848 bhaiya
