### ISSUE TITLE
[Bug] Selecting Same Workspace Again Gives Notification About Workspace is Changed

### ISSUE THREAD

**Issue by Nabhag8848** [RocketChat/Apps.Notion#66]
### What happened?

- When changing workspace again to same connected workspace in dropdown, it gives notification on selecting which we shouldn't get if it is connected to same workspace. 
- Note: Opening and selecting without altering the dropdown works fine - doesn't give notification.

### Steps to reproduce

1. run `/notion ws`
2. select different workspace in dropdown. 
3. again change workspace in dropdown which is already connected.
4. select while you selected the already connected workspace
5. check we are getting notification.

### Relevant ScreenShots

https://github.com/RocketChat/Apps.Notion/assets/65061890/6db3ac8b-36cf-44b7-8e04-e83dfae78ca3

### Version

v6.5.3

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by Sumitwarrior7** [comment]
Hello @Nabhag8848 bhaiya
I would like to work on this issue 
Can you assign this issue to me

**Comment by Nabhag8848** [comment]
@Sumitwarrior7 Assigned go ahead, lemme us know here:  why this is happening before making an PR.

**Comment by Nabhag8848** [comment]
Hey @Sumitwarrior7 Have we found why this happens ?

**Comment by Sumitwarrior7** [comment]
Hello @Nabhag8848 bhaiya, i will start working on it from now, as there was some medical emergency so was not able to work on it

Sorry for inconvenience

**Comment by Sumitwarrior7** [comment]
Hello @Nabhag8848  bhaiya

There are 3 scenarios:
1) When we open dropdown through command and then directly clicks the Select button without clciking dopdown, then there is no notification
2) When we open dropdown through command and then clicks the dropdown button and select the same workspace, then there is notification
3) When we open dropdown through command and then clicks the dropdown button and alter the ws and then again chosen  the same workspace, then there is notification

so, based on above thing, ig issue lies in while clicking the dropdown

# For reference:

[Screencast from 04-03-24 02:18:24 PM IST.webm](https://github.com/RocketChat/Apps.Notion/assets/108853577/4bd885d0-1ea3-4588-8cfd-485eab60bd78)
