### ISSUE TITLE
[Bug] Comments don't support pagination

### ISSUE THREAD

**Issue by JeffreytheCoder** [RocketChat/Apps.Notion#75]
### What happened?

Our App doesn't support pagination of comments. The current implementation fetches [Notion's Comment API](https://developers.notion.com/reference/retrieve-a-comment), which returns max 100 comments. 

We want support pagination comments, like for pages & DBs, which have an existing issue #38 in progress. 

### Steps to reproduce

View comments of a Notion page with 100+ comments

### Version

v6.6.5

### What browsers are you seeing the problem on?

Chrome

**Comment by JeffreytheCoder** [comment]
Working on it

**Comment by Nabhag8848** [comment]
Hey @JeffreytheCoder Are you still working on this ? Let us know if you stuck or have any questions

**Comment by JeffreytheCoder** [comment]
Yes @Nabhag8848 I'm waiting for #59 to go through so I can keep the code style consistent and learn from your reviews there

**Comment by Nabhag8848** [comment]
Thanks @JeffreytheCoder ! I just merged #59
