### ISSUE TITLE
[Bug] : displaying title fields before selecting a page while creating notion db

### ISSUE THREAD

**Issue by Sumitwarrior7** [RocketChat/Apps.Notion#79]
### What happened?

When we use /notion create db command, the modal displays all the fields in it.
But it should display other fields only when a Page is selected

### Steps to reproduce

1. use /notion create db

### Relevant ScreenShots

![Screenshot from 2024-04-11 15-53-32](https://github.com/RocketChat/Apps.Notion/assets/108853577/28e0434a-b521-473d-9b2a-224a0d81e58d)

### Version

v6.8.0

### What browsers are you seeing the problem on?

Chrome

**Comment by Nabhag8848** [comment]
Hey @Sumitwarrior7 those three fields are intended always for every database creation so current implementation is more intuitive than having it dynamic. Thanks ! Closing this.

**Comment by Sumitwarrior7** [comment]
actually what i want to say is that Title of Database and Ttitle Property Name should be displayed only, when we have selected a Page
Correct me if i am wrong @Nabhag8848 bhaiya
